# Generated by Django 5.2.5 on 2025-10-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userfeedback_type_alter_userfeedback_user'),
    ]

    operations = [
    ]
